### ISSUE TITLE
"error trying to start process"

### ISSUE THREAD

**Issue by rdthree** [camnewnham/HotLoader#2]
Hi

I've installed from the package manager and Rhino 8, I didn't see it on the Rhino 7 package manager.  When dropping the component onto the canvas I see this error.  I'm running on Windows 11.

![image](https://github.com/camnewnham/HotLoader/assets/1165540/c7cd244a-a8d2-4a17-86b4-c8b0c006c481)

**Comment by camnewnham** [comment]
Thanks @rdthree 
This was due to Rhino 8's change to dotnet core. Fixed via https://github.com/camnewnham/HotLoader/commit/4c68c6b2291e5faf7c09c98274f45bc31c5fe0a3

**Comment by rdthree** [comment]
Thanks! At this point should I wait for an updated version on the package
manager?

**Comment by camnewnham** [comment]
It's updated now, so yes you can update via the package manager :)

Cheers
