### ISSUE TITLE
Relink?

### ISSUE THREAD

**Issue by jjsolly** [camnewnham/HotLoader#5]
Hi Cam! 

Been finding this extremely useful so thanks a lot! Aware you haven't worked on this for a while but wondered how easy it would be to "relink" a hotloader component to the contents of a previous one.. I have managed to lose the component I had made but obviously I still have the whole folder with .sln and .cs that was generated by it. Embarrassingly this is maybe the third time I've made the same blunder. 

Any tips or tricks much appreciated to avoid having to do a copy/paste exercise. 

Hope all well
James

**Comment by camnewnham** [comment]
Hey James, glad it's useful for you! I've added this feature in `0.0.7-pre`. 
You can place a new `Custom C# Component`, close the source window that opens, and instead right click on the component and `Link to Existing Project`. Let me know if that does the trick :)
Cheers
